packages:
  - apps/*
  - packages/*
  - internal/*

catalog:
  '@types/node': ^22.8.6
  '@manypkg/get-packages': ^2.2.2
  'prettier': ^3.3.3
  'prettier-plugin-tailwindcss': ^0.6.8

ignoredBuiltDependencies:
  - esbuild
